spring:
  application:
    name: classifier-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg_db:5432/classifier_service?currentSchema=security
    username: classifier_app_user
    password: 123
