spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5433/account_service
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20

server:
  port: 9090